repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the sha / tag you want to point at
    hooks:
      - id: check-xml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: php-cs-fixer
        files: \.(php)$
        entry: ./vendor/bin/php-cs-fixer fix ./app/code/
        args:
          - --config=./.php-cs-fixer.dist.php
        language: system
  - repo: https://github.com/netz98/pre-commit-php
    rev: 1.3.0  # Use the sha / tag you want to point at
    hooks:
      - id: php-lint
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-stan
        files: \.(php)$
        args:
          - app/code --level=4
  - repo: https://gitlab.com/daverona/pre-commit/php
    rev: 0.6.0          # use the most recent version
    hooks:
      # Hooks using native
      - id: phpmd         # static analyzer for PHP code
  - repo: local
    hooks:
      - id: phpcs
        name: phpcs
        files: \.(php)$
        entry: ./vendor/bin/phpcs
        language: system
        args:
          - --standard=PSR12
          - --colors
          - -p
          - ./app/code/
